//// <auto-generated />
//using System;
//using ATM.Database;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

//#nullable disable

//namespace ATM.Migrations
//{
//    [DbContext(typeof(ATMContext))]
//    partial class ATMContextModelSnapshot : ModelSnapshot
//    {
//        protected override void BuildModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "8.0.2")
//                .HasAnnotation("Relational:MaxIdentifierLength", 128);

//            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

//            modelBuilder.Entity("ATM.Database.Models.Account", b =>
//                {
//                    b.Property<string>("AccountNo")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<double>("Balance")
//                        .HasColumnType("float");

//                    b.Property<int>("CardNumber")
//                        .HasColumnType("int");

//                    b.Property<string>("FullName")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int>("Pin")
//                        .HasColumnType("int");

//                    b.HasKey("AccountNo");

//                    b.ToTable("accounts");
//                });

//            modelBuilder.Entity("ATM.Database.Models.Transaction", b =>
//                {
//                    b.Property<Guid>("TransactionId")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("uniqueidentifier");

//                    b.Property<string>("AccountNo")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<double>("TransactionAmount")
//                        .HasColumnType("float");

//                    b.Property<DateTime>("TransactionDate")
//                        .HasColumnType("datetime2");

//                    b.Property<int>("TransactionType")
//                        .HasColumnType("int");

//                    b.HasKey("TransactionId");

//                    b.HasIndex("AccountNo");

//                    b.ToTable("transactions");
//                });

//            modelBuilder.Entity("ATM.Database.Models.Transaction", b =>
//                {
//                    b.HasOne("ATM.Database.Models.Account", "Account")
//                        .WithMany("Transaction")
//                        .HasForeignKey("AccountNo")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("Account");
//                });

//            modelBuilder.Entity("ATM.Database.Models.Account", b =>
//                {
//                    b.Navigation("Transaction");
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
